"""
Creating mesh for the 2D plate 12 mm x 12 mm with a hole 1 mm in diameter, located in the centre.
"""

import math as m

h = 50.0  # mesh step [m]
N_r   = 4 # + 1
N_phi = 16 
N_CELLS = N_r * N_phi


points = []
cells = []

# Generate mesh
for i in range(N_r+1):
	r = 0.5 + i * (6.0 - 0.5) / N_r  # mm
	r *= 1e-3  # m
	for j in range(N_phi):
		phi = j * 2 * m.pi / N_phi
		k = 1.0  # prolongation to fit square
		# FIXME
		# N_phi = 8
		#if i > 0 and j % 2:
		#	kx = ky = m.sqrt(2)
		# N_phi = 16
		# if i > 0:
		# 	if   j % 4 == 3:
		# 		k = 1.0 / m.cos(m.pi / 8)
		# 	elif j % 4 == 2:
		# 		k = 1.0 / m.cos(m.pi / 4)
		# 	elif j % 4 == 1:
		# 		k = 1.0 / m.cos(m.pi / 8)

		if   j % 4 == 3:
			k = 1.0 + (1.0 / m.cos(m.pi / 8) - 1.0) * i / N_r
		elif j % 4 == 2:
			k = 1.0 + (1.0 / m.cos(m.pi / 4) - 1.0) * i / N_r
		elif j % 4 == 1:
			k = 1.0 + (1.0 / m.cos(m.pi / 8) - 1.0) * i / N_r
		points.append( (6e-3 + k * r * m.cos(phi), 6e-3 + k * r * m.sin(phi) ) )


print(len(points), ' points total.')


# with open('mesh_basic.mesh', 'w') as f:
# 	f.write('MFEM mesh v1.0\n\ndimension\n2\nelements\n')
# 	print(N_CELLS, file=f)
# 	for i in range(N_CELLS):
# 		f.write('{} 3 {} {} {} {}\n'.format())



# Write mesh to VTK file in the UNSTRUCTURED_GRID format
with open('mesh_basic2.vtk', 'w') as f:
	# write header
	f.write('# vtk DataFile Version 3.0\n')
	f.write('Generated by a hand-made script\n')
	f.write('ASCII\n')
	f.write('DATASET UNSTRUCTURED_GRID\n')

	# write point coordinates
	f.write(' '.join(['POINTS', str(len(points)), 'double\n']))
	for point in points:
		f.write('{:13.12f} {:13.12f} 0\n'.format(point[0], point[1]))


	# write cells
	f.write(' '.join(['CELLS', str(N_CELLS), str(5 * N_CELLS), '\n']))  # *by 5 means 1 + num_of_nodes_per_cell
	i = 0
	while i < (len(points) - N_phi):
		if not ( (i+1) % N_phi == 0):
			f.write( '4 {} {} {} {}\n'.format(i, i+N_phi, i+N_phi+1, i+1) )
		else:
			f.write( '4 {} {} {} {}\n'.format(i, i+N_phi, i+1, i+1-N_phi) )
		i += 1

	
	f.write(' '.join(['CELL_TYPES', str(N_CELLS), '\n']))
	for _ in range(N_CELLS):
		f.write('9\n')  # magic constant for VTK_QUAD

	# write material attributes for each cell
	f.write(' '.join(['CELL_DATA', str(N_CELLS), '\n']))
	f.write('SCALARS material int\n')
	f.write('LOOKUP_TABLE default\n')
	for i in range(N_CELLS):
		f.write('{}\n'.format(i+1))

